<a href="https://colab.research.google.com/github/vaddisiva/new/blob/main/Advertisement_sale_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
dataset=pd.read_csv('DigitalAd_dataset.csv')
dataset

Age  Salary  Status
0     18   82000       0
1     29   80000       0
2     47   25000       1
3     45   26000       1
4     46   28000       1
..   ...     ...     ...
395   35   65000       0
396   26   80000       0
397   26   52000       0
398   20   86000       0
399   32   18000       0

[400 rows x 3 columns]

# New Section

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
print(dataset.shape)
print(dataset.head(5))

(400, 3)
   Age  Salary  Status
0   18   82000       0
1   29   80000       0
2   47   25000       1
3   45   26000       1
4   46   28000       1


In [ ]:
print(dataset.tail(5))

     Age  Salary  Status
395   35   65000       0
396   26   80000       0
397   26   52000       0
398   20   86000       0
399   32   18000       0


Separating the data set

In [ ]:
x=dataset.iloc[:,:-1].values
x

array([[    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],
       [    27,  17000],
       [    33,  51000],
       [    35, 108000],
       [    30,  15000],
       [    28,  84000],
       [    23,  20000],
       [    25,  79000],
       [    27,  54000],
       [    30, 135000],
       [    31,  89000],
       [    24,  32000],
       [    18,  44000],
       [    29,  83000],
       [    35,  23000],


In [ ]:
y=dataset.iloc[:,-1].values
y

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)
print(x_train)

[[ 0.97446763  0.56400811]
 [-1.52088611 -1.28151705]
 [ 0.30264162  0.03671521]
 [-0.36918439 -0.81281224]
 [ 0.49459191  1.20847722]
 [-0.1772341   0.82765456]
 [-0.27320924 -0.78351819]
 [ 0.39861676  0.24177356]
 [-0.27320924  0.00742116]
 [ 0.01471619 -0.60775389]
 [ 0.11069133  0.00742116]
 [-0.46515953  2.29235707]
 [ 0.39861676 -0.02187289]
 [-0.27320924 -1.28151705]
 [ 1.93421906 -1.39869325]
 [-0.27320924  2.23376897]
 [ 0.11069133  1.03271291]
 [-0.56113467  1.44282962]
 [ 0.97446763  1.85294632]
 [ 0.30264162  0.03671521]
 [-1.13698554 -1.04716465]
 [-0.08125895  0.27106761]
 [ 0.30264162 -0.54916579]
 [-0.27320924 -0.60775389]
 [ 0.87849248 -1.39869325]
 [ 0.78251734 -0.34410744]
 [-0.46515953 -1.252223  ]
 [ 0.20666648  0.12459736]
 [ 0.39861676  0.97412481]
 [-0.56113467  1.35494747]
 [-0.46515953 -0.05116694]
 [-0.56113467  2.32165112]
 [-0.75308496  0.27106761]
 [ 1.16641791 -0.78351819]
 [ 0.20666648  1.06200696]
 [ 0.20666648 -0.40269554]
 [ 0.30264162 -0.31481339]
 

In [ ]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [ ]:
y_pred=model.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score
print("Accuracy of the model : {0}%".format(accuracy_score(y_test,y_pred)*100))

Accuracy of the model : 80.0%


In [ ]:
age=int(input("Enter new customer age:"))
sal=int(input("Enter new customer salary:"))
newcust=[[age,sal]]
result=model.predict(sc.transform(newcust))
print(result)
if (result==1):
  print("Customer will buy")
else:
  print("customer won't buy")

Enter new customer age:48
Enter new customer salary:50000
[1]
Customer will buy


In [ ]:
!zip -r /content/lib:zip /content/


  adding: content/ (stored 0%)
  adding: content/.config/ (stored 0%)
  adding: content/.config/gce (stored 0%)
  adding: content/.config/default_configs.db (deflated 98%)
  adding: content/.config/configurations/ (stored 0%)
  adding: content/.config/configurations/config_default (deflated 15%)
  adding: content/.config/.last_survey_prompt.yaml (stored 0%)
  adding: content/.config/.last_opt_in_prompt.yaml (stored 0%)
  adding: content/.config/.last_update_check.json (deflated 22%)
  adding: content/.config/logs/ (stored 0%)
  adding: content/.config/logs/2023.10.05/ (stored 0%)
  adding: content/.config/logs/2023.10.05/19.32.16.008139.log (deflated 58%)
  adding: content/.config/logs/2023.10.05/19.32.59.577697.log (deflated 56%)
  adding: content/.config/logs/2023.10.05/19.31.42.136492.log (deflated 91%)
  adding: content/.config/logs/2023.10.05/19.32.58.628417.log (deflated 57%)
  adding: content/.config/logs/2023.10.05/19.32.44.892388.log (deflated 58%)
  adding: content/.config/lo